[build]
    command = "sudo apt-get update && sudo apt-get install -y libpq-dev && npm install && npm build"
    functions = "functions"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/"
    status = 200

[build.environment]
    NETLIFY_DEV_ALLOW_EXTERNAL = "pg-query-stream sqlite3"
